# Generated by Django 3.2.6 on 2021-08-17 14:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="teacher.teacher",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homeworkresult",
            name="done",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
