# Generated by Django 3.2.6 on 2021-08-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_auto_20210817_1700"),
        ("teacher", "0003_auto_fill_tables"),
    ]

    operations = []
