"""
Write a function that gets file path as an argument.
Read the first line of the file.
If first line is a number return true if number in an interval [1, 3)*
and false otherwise.
In case of any error, a ValueError should be thrown.
Write a test for that function using pytest library.
You should create files required for the testing inside the test run and remove them after the test run.
(Opposite to previous homeworks when you used files created manually before the test.)
Definition of done:
 - function is created
 - function is properly formatted
 - function has positive and negative tests
 - tests do a cleanup and remove remove files generated by tests
"""


def number_returning_function(file_path):
    try:
        with open(file_path) as fi:
            first_line = int(fi.readline().rstrip("\n"))
        if 1 <= first_line < 3:
            return True
        else:
            return False
    except ValueError:
        raise
